#!/usr/bin/env python3
"""tools/bitlevel/gen_fixture.py — emit the one-opcode fixture at width W.

ONE program, TWO spellings, selected when the emitted file is compiled:
  -DBITLEVEL=0  the OPCODE spelling: unsigned `+` at width W, lowered by the
                pass to cq_template_add_i<W> and realised by K6.
  -DBITLEVEL=1  the BIT-LEVEL spelling: the SAME construction — K6's ripple
                carry, t = a^b ; s = t^c ; c' = (a&b) ^ (t&c) — written over
                tainted `bool`s, so the pass sees `xor i1` / `and i1` and
                lowers each to a 1-bit template. This is what a bit-level
                lowering (or an expand-then-reoptimise pipeline) would hand
                the pass, written out so that neither repo needs a change.
  -DCHAIN=0     four DISTINCT tainted addends (nothing for clang to fold);
  -DCHAIN=1     the SAME addend four times (clang folds x+y+y+y+y at the
                opcode level to x+(y<<2) before the pass runs).
Both spellings taint the same bits with the same Ry and measure W bits, so
the whole difference is the four-deep add chain. argc > 1 is CLASSICAL mode
(θ = π folds every Ry to a bit flip): both must print (~X + 4·~Y) mod 2^W.

usage: gen_fixture.py W > addchain_W.cq.c
"""
import sys

CTYPE = {8: "unsigned char", 16: "unsigned short", 32: "unsigned int",
         64: "unsigned long long"}
X0 = 0x3579BDF1A2C4E6F5
Y0 = 0x2B4D6E8F13579BDF


def expect(w, nadd=4):
    m = (1 << w) - 1
    return (((~X0) & m) + nadd * ((~Y0) & m)) & m


def emit(w):
    m = (1 << w) - 1
    x0, y0 = X0 & m, Y0 & m
    o = []
    p = o.append
    p("/* GENERATED by tools/bitlevel/gen_fixture.py — the one-opcode experiment "
      f"at W={w}. */")
    p("#include <math.h>\n#include <stdio.h>\n#include <stdbool.h>")
    p("#ifndef BITLEVEL\n#define BITLEVEL 0\n#endif\n#ifndef CHAIN\n#define CHAIN 0\n#endif")
    p(f"#define X0 {x0:#x}u\n#define Y0 {y0:#x}u")
    p("#if !BITLEVEL")
    t = CTYPE[w]
    p("int main(int argc, char **argv)\n{")
    p("    double theta = (argc > 1) ? M_PI : M_PI / 2.0;")
    p(f"    {t} x = X0, y1 = Y0, y2 = Y0, y3 = Y0, y4 = Y0, s, u, v, w;")
    p("    (void)argv;\n    x  = cq_theta(x, theta);\n    y1 = cq_theta(y1, theta);")
    p("#if CHAIN\n    y2 = y1; y3 = y1; y4 = y1;\n#else")
    p("    y2 = cq_theta(y2, theta);\n    y3 = cq_theta(y3, theta);\n    y4 = cq_theta(y4, theta);\n#endif")
    p(f"    s = ({t})(x + y1);\n    u = ({t})(s + y2);\n    v = ({t})(u + y3);\n    w = ({t})(v + y4);")
    p('    printf("addchain -> %llu\\n", (unsigned long long)cq_measure(w));\n    return 0;\n}')
    p("#else")
    p("#define BIT(v, i) ((bool)(((v) >> (i)) & 1u))")
    p("int main(int argc, char **argv)\n{")
    p("    double theta = (argc > 1) ? M_PI : M_PI / 2.0;\n    unsigned long long r = 0;\n    (void)argv;")

    def taint(pfx, const):
        for i in range(w):
            p(f"    bool {pfx}{i} = cq_theta(BIT({const}, {i}), theta);")

    def add(a, b, s):
        # K6's five-gate order per lane; the top lane produces no carry-out.
        p(f"    bool " + ", ".join(f"{s}{i}" for i in range(w)) + ";")
        p("    {")
        p("        bool " + ", ".join(f"c{i}" for i in range(1, w)) + ";" if w > 1 else "")
        for i in range(w):
            ci = "false" if i == 0 else f"c{i}"
            p(f"        {{ bool t = {a}{i} ^ {b}{i}; {s}{i} = t ^ {ci};" +
              (f" c{i+1} = ({a}{i} & {b}{i}) ^ (t & {ci}); }}" if i < w - 1 else " }"))
        p("    }")

    taint("a", "X0")
    taint("b", "Y0")
    p("#if CHAIN")
    add("a", "b", "s")
    add("s", "b", "u")
    add("u", "b", "v")
    add("v", "b", "w")
    p("#else")
    taint("d", "Y0")
    taint("e", "Y0")
    taint("f", "Y0")
    add("a", "b", "s")
    add("s", "d", "u")
    add("u", "e", "v")
    add("v", "f", "w")
    p("#endif")
    for i in range(w):
        p(f"    r |= (unsigned long long)cq_measure(w{i}) << {i};")
    p('    printf("addchain -> %llu\\n", r);\n    return 0;\n}')
    p("#endif")
    return "\n".join(o) + "\n"


if __name__ == "__main__":
    sys.stdout.write(emit(int(sys.argv[1])))
