/* src/kernels/fdiv.h — M35, K17. `fdiv` at f64: `soft_fdiv` as a Rule 7
 * kernel. PRD-v2 §5's M35 row, §7.1-7.4, §7.6, §7.12, §7.16.
 *
 * Read docs/constructions/K17.md before changing anything here. Every gate is
 * a port: `soft_fdiv` (third_party/bennett/src/softfloat/fdiv.jl:44-139) and
 * the five shared helpers it calls (softfloat_common.jl:23-24, :68-105,
 * :113-139, :174-191, :198-227), transcribed ONE ROW PER OPERATOR OCCURRENCE
 * in source order (§7.2's literal grain) over the step blocks M14, M16, M17,
 * M31 and M32 already export, plus upstream's own four-gate bitwise
 * vocabulary. Nothing in this module is a construction of ours.
 *
 * THE LOOP IS TRANSCRIBED PER OPERATOR AND THAT IS PRD-v2 §7.16's DECISION,
 * NOT THIS MODULE'S. §5's M35 row used to say the 56-iteration restoring loop
 * "should compose M19's exported step block, not transcribe it"; K17.md §5.1
 * measured that that instruction and §7.2's literal grain select DIFFERENT
 * constructions here — the loop's middle three lines are operator-for-operator
 * K12's P1/P2/P3 at W = 64 with the same bindings and the same raw-flag
 * convention, but its two ENDS are not K12's at all (there is no dividend bit
 * to shift in, and the quotient is `q = (q << 1) | ifelse(fits, 1, 0)`, a
 * view + a mux + an `or` where K12's P4 is one CX), and it runs 56 times over
 * 64-bit spans where `cq_divrem_steps`/`_region` are functions of W alone. The
 * maintainer settled it at the Wave 4 boundary (PRD-v2 §7.16): TRANSCRIBE PER
 * OPERATOR — K17.md's option B — and the "compose M19" instruction is RETIRED
 * for `fdiv` exactly as K21 had already read the M40 row. Driving
 * `cq_divrem_block` at W = 112 with dividend `ma << 55` is the only arithmetic
 * that works and it is a RE-DERIVATION (Rule 1), at ~2.5x the slots and ~2.6x
 * the qubits, at a width the ABI never ships. Do not reopen it in code.
 *
 * K17 STILL TRANSCRIBES NO GATE LIST. Every gate of the loop body comes out of
 * `cq_ult_step`, `cq_sub_step`, `cq_mux_step` or the inline `or`, which is
 * plan §0.4 / PRD §15 D9(e) satisfied — the same thing `divrem_u.h` says M19
 * itself is.
 *
 * THE SHAPE IS M34's AND M32's: A ROW TABLE PLUS A STEP MACHINE. A row is one
 * upstream lowering function applied once, or a VIEW, or a projection of a
 * hand-off's tuple. The kernel is ONE cq_sandwich over ONE flat region whose
 * step function dispatches a global index into those blocks (PRD-v2 §7.1,
 * src/kernels/divrem_u.c's shape).
 *
 * THE TABLE IS IN THREE SEGMENTS AND THE MIDDLE ONE IS GENERATED BY A LOOP.
 * 478 rows is too many to write out and — more to the point — 56 hand-copied
 * iterations would be 56 independent chances at the one mistake PRD-v2 §7.1
 * says a kernel of this shape actually makes. So the program is a PRE table
 * (phases A-G), an ITERATION TEMPLATE of CQ_FDIV_ITER_ROWS rows instantiated
 * CQ_FDIV_N_ITERS times, and a POST table (phases I-N); `cq_fdiv_row_at`
 * materialises row `i` with its operand references REBASED to absolute row
 * indices. THE PROGRAM IS STILL 478 ROWS: every iteration has its own slots
 * and its own spans, nothing is shared between iterations beyond the source's
 * own data flow, and `tests/test_kernel_fdiv_spans.inc` walks every one of
 * them — a K12-shaped slide that aliased iteration `t` onto `t-1` is exactly
 * what that scan exists to see.
 *
 * FIVE SEAMS WERE RECORDED BEFORE A LINE WAS WRITTEN AND FOUR ARE FILE CUTS
 * (bd a-row-table-fp-kernel-needs-three-seams-not-two: "record FOUR seams in
 * advance for M34/M35/M39/M40, not two, and expect the PRD's own recorded seam
 * to be RETIRED AS A FILE SEAM in every one of them").
 *
 *   fdiv.c          the ROW TABLES and nothing else — the port a reader checks
 *                   against the Julia.
 *   fdiv_step.c     the COSTS and the LAYOUT: what a row costs (ASKED of
 *                   M14/M16/M17/M31/M32) and where its spans lie. Knows no
 *                   Julia.
 *   fdiv_operand.c  OPERAND RESOLUTION: the collapsing view chain, the
 *                   constant vocabulary, the block outputs, the hand-off
 *                   projections and the one-bit flags.
 *   fdiv_emit.c     the DISPATCH and the SURFACE: which gate a slot emits, the
 *                   public block, and the Rule 7 entry point. `fdiv_int.h` is
 *                   the seam between these three (M32's D-K23-10, M33's
 *                   COSTS-AND-LAYOUT <-> OPERAND RESOLUTION).
 *   fdiv_eval.c     the CLASSICAL body, which emits nothing (M32's `_eval` <->
 *                   THE CIRCUIT seam).
 *
 * PRD-v2 §5's own recorded seam — THE 56-BIT RESTORING LOOP <-> PRE-NORMALISATION
 * — is NOT taken as a FILE seam, for M34's and M33's reason: splitting the
 * table would put ONE prefix sum in two files, which K15.md's and K16.md's
 * seam boxes both refuse ("the prefix-sum table stays in one place, because
 * two tables is two chances to get the decode wrong"). It survives as a NAMED
 * ROW BOUNDARY — `cq_fdiv_loop_base_row()` below — with a case pinning what
 * crosses it, which is the claim the file split was standing in for.
 *
 * SLOTS AND GATES COME APART, AS THEY DO IN M31, M32, M33, M34 AND M36
 * (D-K18-6). §7.3's constants are `const cq_bit` SOURCES and a mask or shift
 * by a compile-time constant is a VIEW, so classical lanes sit inside block
 * operands at EVERY operand mask including the all-quantum one L4 pins — 125
 * of K17's 478 rows are views. `cq_fdiv_steps` is a SLOT count and is never a
 * gate count; every composition identity over this module is over slots.
 *
 * W MUST BE 64. PRD-v2 §1 scopes v2 to `f64` and `soft_fdiv` is
 * `(UInt64, UInt64)`, so any other width is a fiction rather than an
 * unimplemented case, and is a hard error in BOTH configurations.
 */
#ifndef CQOPS_KERNELS_FDIV_H
#define CQOPS_KERNELS_FDIV_H

#include "bit.h"
#include "ctx.h"
#include "kernels/fpfield.h"
#include "scratch.h"

#include <stdint.h>

/* --- The program: one row per operator occurrence (PRD-v2 §7.2). ---------- */

/* Each row is ONE upstream lowering function applied once, a VIEW, or a
 * projection. The blocks are M16's `cq_eq_step` (lower_eq!, arith.jl:424-447)
 * and `cq_ult_step` (lower_ult!, :449-463); M14's `cq_add_step` (lower_add!,
 * adder.jl:1-18) and `cq_sub_step` (lower_sub!, :148-172); M17's `cq_mux_step`
 * (lower_mux!, arith.jl:522-532); M31's `cq_fp_class_step`; M32's four
 * shared-helper blocks; and the four bitwise ops emitted directly one gate per
 * slot as PRD-v2 §7.10 directs — `lower_or!` (arith.jl:274-282), `lower_xor!`
 * (:284-291), `lower_and!` (:268-272) and `lower_not1!` (:474-478).
 *
 * THERE IS NO `mul` ROW AND NO `slt` ROW, AND BOTH ABSENCES ARE MEASURED
 * (K17.md §5.9). `soft_fdiv` contains no `*` at all, and every ordered compare
 * in its own body is an `==`, a `!=` or the loop's UNSIGNED `r >= mb`; all
 * eight signed compares the port performs live inside M32's two helpers. A
 * `cq_slt_block` appearing here would mean the audit was wrong.
 *
 * THE SIX CLASS PREDICATES COMPOSE M31's BLOCK AND ARE NOT TRANSCRIBED AGAIN
 * (K17.md D-K17-5). `fdiv.jl:56-61` is `fadd.jl:29-34` and `fmul.jl:31-36` row
 * for row, and is exactly M31's `is_nan` / `is_inf` / `is_zero`, so K17 spends
 * six `CQ_FDOP_CLASS` rows on them instead of the twenty-eight `eq` + `not1` +
 * `and1` rows the literal grain would give. The SLOTS AND THE BITS ARE
 * IDENTICAL EITHER WAY, so this is not a cost decision: it is Rule 1 applied
 * to the call graph, and M33/M34/M36 all compose the same block.
 *
 * `CQ_FDOP_` AND NOT `CQ_FDIV_`: M36 measured that a row-op enum colliding
 * with a neighbouring enum renumbers it silently (C enums share one
 * namespace), so the op names are deliberately unlike everything else here. */
typedef enum {
    CQ_FDOP_VIEW = 0,  /* 0 slots, 0 bits: `(s0 >> shift) & mask`         */
    CQ_FDOP_OUT,       /* 0 slots, 0 bits: output `s1` of hand-off `s0`   */
    CQ_FDOP_CLASS,     /* M31: `s1` is a cq_fp_class over the 64-lane s0  */
    CQ_FDOP_EQ,        /* 2 x 64 -> 1 bit; the RAW wire is `a != b`       */
    CQ_FDOP_ULT,       /* 2 x 64 -> 1 bit; the RAW wire is `a >=u b`      */
    CQ_FDOP_ADD,       /* 2 x 64 -> 64                                    */
    CQ_FDOP_SUB,       /* 2 x 64 -> 64                                    */
    CQ_FDOP_MUX,       /* cond(1) + 2 x 64 -> 64                          */
    CQ_FDOP_OR,        /* 2 x 64 -> 64                                    */
    CQ_FDOP_XOR,       /* 2 x 64 -> 64                                    */
    CQ_FDOP_NORM52,    /* _sf_normalize_to_bit52  -> (m, e)               */
    CQ_FDOP_CLZ,       /* _sf_normalize_clz       -> (wr, exp)            */
    CQ_FDOP_SUBNORM,   /* _sf_handle_subnormal    -> five values          */
    CQ_FDOP_ROUND,     /* _sf_round_and_pack      -> four values          */
    CQ_FDOP_NOT1,      /* 1 bit -> 1 bit                                  */
    CQ_FDOP_AND1,      /* 2 x 1  -> 1 bit                                 */
    CQ_FDOP_OR1,       /* 2 x 1  -> 1 bit                                 */
    CQ_FDOP_N_OP
} cq_fdiv_op;

_Static_assert(CQ_FDOP_VIEW == 0,
               "a zero-initialised row must be the free one; a renumbering "
               "must break a build, not just a comment");

/* THE VOCABULARY HAS NO SIGNED COMPARE AND NO MULTIPLY, AND BOTH ABSENCES ARE
 * MEASUREMENTS RATHER THAN OMISSIONS (K17.md §5.9). Pinned here because a
 * comment cannot stop an eighteenth op arriving, and because the substitution
 * this refusal is aimed at is INVISIBLE to everything else: putting an `slt`
 * where an `ult` belongs leaves the gate SHAPE, the palindrome, the slot scan
 * and the scratch all correct and the answer wrong exactly on the underflow
 * path — K9's `uge`-meaning-`ule` in a new dress, and K23 §5.4's live hazard
 * one module over, where EIGHT of M32's nine ordered compares ARE signed.
 * `soft_fdiv`'s own body has none: every ordered compare it spells is the
 * loop's UNSIGNED `r >= mb` at fdiv.jl:93. */
_Static_assert(CQ_FDOP_N_OP == 17,
               "M35's op vocabulary is seventeen and contains no `slt` and no "
               "`mul`; adding an eighteenth must be a deliberate act that "
               "breaks this build, not a comment nobody reads");

/* An operand slot: `>= 0` names an earlier ROW of the same program, and each
 * negative code below names something that owns no qubit at all — a rail or a
 * constant span (§7.3). A constant and a view are only ever CONTROLS, so they
 * reach the emitter through cq_emit_*'s `const cq_bit *` parameters and can
 * never be materialised: I6(a) by construction.
 *
 * THERE IS NO `K_7FF` HERE AND `fmul` NEEDS ONE, WHICH IS WORTH SAYING.
 * `0x7FF` occurs in `soft_fdiv` at :48 and :51 only, as the MASK of
 * `(a >> 52) & 0x7FF` — wiring, §7.3 as amended. Its other reading, the right
 * operand of `ea == 0x7FF`, occurs only inside the class predicates at :56-59,
 * and those compose M31's block, which owns the constant. A port that added a
 * `K_7FF` code here would be carrying a constant nothing compares against. */
enum {
    CQ_FD_A          = -1,   /* the rail `a`                    fdiv.jl:44  */
    CQ_FD_B          = -2,   /* the rail `b`                                */
    CQ_FD_K_ZERO     = -3,   /* `UInt64(0)`                     :66-69, :101 */
    CQ_FD_K_ONE      = -4,   /* `UInt64(1)` / `Int64(1)`        :68, :95    */
    CQ_FD_K_BIAS     = -5,   /* `BIAS = Int64(1023)`            :45, :81    */
    CQ_FD_K_IMPLICIT = -6,   /* softfloat_common.jl:9           :66, :67    */
    CQ_FD_K_INF      = -7,   /* softfloat_common.jl:11          :63         */
    CQ_FD_K_QUIET    = -8,   /* softfloat_common.jl:13          :136        */
    CQ_FD_K_INDEF    = -9,   /* softfloat_common.jl:14          :130, :133  */
    CQ_FD_N_CODE     = 9
};

/* `shift` is the RIGHT-shift amount and a NEGATIVE value is a left shift, so a
 * chain of views composes to one `(shift, mask)` pair — see fdiv_operand.c.
 * Both are read only when `op == CQ_FDOP_VIEW`; `s1` doubles as the output
 * index of a `CQ_FDOP_OUT` row. */
typedef struct {
    short    op;             /* a cq_fdiv_op                              */
    short    s0, s1, s2;     /* operands; only the first arity(op) read   */
    short    shift;          /* VIEW only                                 */
    uint64_t mask;           /* VIEW only                                 */
} cq_fdiv_row;

/* The outputs of the four M32 hand-offs, in the order softfloat_common.jl
 * returns them — :104, :138, :190 and :226. `_sf_round_and_pack` returns FOUR
 * although its docstring at :194 names three; the CODE is the specification. A
 * `CQ_FDOP_OUT` row's `s1` is one of these. */
enum {
    CQ_FD_OUT_M          = 0, /* norm52  :104  m_final                     */
    CQ_FD_OUT_E          = 1, /* norm52  :104  e_final                     */
    CQ_FD_OUT_WR         = 0, /* clz/subnorm   wr                          */
    CQ_FD_OUT_EXP        = 1, /* clz/subnorm   result_exp                  */
    CQ_FD_OUT_FLUSHED    = 2, /* subnorm :190  flushed_result (a VIEW)     */
    CQ_FD_OUT_SUBNORMAL  = 3, /* subnorm :190  subnormal       (1 bit)     */
    CQ_FD_OUT_FTZ        = 4, /* subnorm :190  flush_to_zero   (1 bit)     */
    CQ_FD_OUT_NORMAL     = 0, /* round   :226  normal_result               */
    CQ_FD_OUT_OVERFLOW   = 1, /* round   :226  overflow_result — DISCARDED */
    CQ_FD_OUT_EXPOVF     = 2, /* round   :226  exp_overflow    (1 bit)     */
    CQ_FD_OUT_EXPOVF_AFT = 3  /* round   :226  ..._after_round (1 bit)     */
};

/* `for i in 0:55` (fdiv.jl:91) and the seven rows of its body. Both are the
 * SOURCE's, not ours: 56 is decoupled from the 64-bit spans and is what
 * fdiv.jl:13-14's invariant needs ("ma, mb in [2^52, 2^53), so the true
 * quotient ma/mb in [1/2, 2) and fits in 56 bits with 55 fractional bits").
 * Pinned rather than commented, so an "obvious" 64 breaks the build. */
enum { CQ_FDIV_N_ITERS = 56, CQ_FDIV_ITER_ROWS = 7 };

/* An upper bound on the PRE and POST segment lengths (36 and 50 as shipped).
 * The step machine's prefix arrays are this long, so a table that outgrows one
 * must fail to BUILD rather than overrun a stack array; asserted in fdiv.c
 * against both real lengths rather than commented. The LOOP needs no such
 * bound — its prefix array is CQ_FDIV_ITER_ROWS long whatever
 * CQ_FDIV_N_ITERS is, which is the whole point of the segmented decode. */
enum { CQ_FDIV_MAX_SEG = 64 };

_Static_assert(CQ_FDIV_N_ITERS == 56 && CQ_FDIV_ITER_ROWS == 7,
               "fdiv.jl:91 is `for i in 0:55` and its body is five emitting "
               "operators and two views; changing either is a re-derivation "
               "and must break a build");

/* The three segment boundaries, as ROW indices into the whole program. `pre`
 * is phases A-G, the loop is CQ_FDIV_N_ITERS x CQ_FDIV_ITER_ROWS, and `post`
 * is phases I-N. `cq_fdiv_loop_base_row()` is PRD-v2 §5's recorded
 * PRE-NORMALISE <-> LOOP seam as a named row boundary (see the header note). */
int cq_fdiv_n_rows(void);
int cq_fdiv_loop_base_row(void);
int cq_fdiv_post_base_row(void);

/* Row `i` of the program, with every operand reference REBASED to an absolute
 * row index of this program. Out of range is a hard error in both
 * configurations. This is the only way to read the table: there is no shared
 * `cq_fdiv_row *` array, because 392 of the 478 rows are instantiated from one
 * template and materialising them would be mutable state the library has no
 * business holding (Rule 13). */
void cq_fdiv_row_at(int i, cq_fdiv_row *out);

/* The ITERATION TEMPLATE itself, with its operand references UNREBASED — the
 * relative codes fdiv.c documents. Exposed so a test can assert that every one
 * of the 56 instantiations is this template at a distinct offset, which is the
 * claim "the loop is one construction run 56 times" reduces to. */
const cq_fdiv_row *cq_fdiv_iter_template(int *n);

/* How many of s0/s1/s2 a row reads. A VIEW reads one and an OUT reads `s0` as
 * a row plus `s1` as an output INDEX, which is not an operand. */
int cq_fdiv_arity(int op);

/* The width of row `i`'s value: 64, 1, or 0 for a hand-off row, whose value is
 * a TUPLE and which may only be named through a `CQ_FDOP_OUT` row. Takes the
 * row table as a parameter so a malformed table can be driven by a death case
 * (M34's shape). */
int cq_fdiv_row_width(const cq_fdiv_row *rows, int n, int i);

/* The same for row `i` OF THE SHIPPED PROGRAM, which has no `cq_fdiv_row *` to
 * pass. One implementation behind both: the array form exists so a death case
 * can drive a malformed table, and this one is what the operand resolver and
 * the well-formedness case use. */
int cq_fdiv_width_at(int i);

/* --- The block. ---------------------------------------------------------- */

/* `a` and `b` are CQ_FP64_W lanes each and are CONTROLS ONLY. THE BLOCK
 * ALLOCATES NOTHING: the caller supplies `scr` and `off` and every span is
 * `off`-relative, which is load-bearing rather than tidy — a block cannot see
 * its own offset, so dropping `off` slides the whole program inside the
 * caller's region and leaves the value, the palindrome, the pool, every gate
 * count AND the slot scan all correct (M18's, M31's and M34's measured
 * finding). Only a SECOND program at a SECOND offset in one region sees it. */
typedef struct {
    const cq_bit *a, *b;
    cq_scratch   *scr;
    uint32_t      off;
} cq_fdiv_block;

/* How many bits of the caller's region the program owns, starting at `off` —
 * the sum over rows of each row's own internals, every term ASKED of its
 * module. Never written as a number here or in a test. */
uint32_t cq_fdiv_region(void);

/* The SLOT count: the sum over rows of each block's step count, asked of its
 * owning module at width 64. ONE INVOLUTION PER SLOT, which is what makes
 * cq_sandwich's index reversal be gate reversal. NOT a gate count. */
int cq_fdiv_steps(void);

/* The slots ONE iteration of fdiv.jl:91-98 costs — K17.md §2.7's `loop_K`,
 * which is `C_ult + C_sub + 2*C_mux + C_or` and is ASKED of M14/M16/M17 rather
 * than written down. Exported because a wrong `loop_K` is a wrong step decode
 * at 56 places at once, so it wants an assertion of its own that names it. */
int cq_fdiv_iter_steps(void);

/* The bits ONE iteration owns. Same reason. */
uint32_t cq_fdiv_iter_region(void);

/* One gate of the program, `u` in [0, cq_fdiv_steps()). Out of range is a hard
 * error in BOTH configurations, for cq_eq_step's reason: an off-by-one lands
 * inside some inner block's OR-prefix or carry chain and emits a plausible
 * wrong gate rather than failing. */
void cq_fdiv_step(cq_ctx *ctx, const cq_fdiv_block *k, int u);

/* `result` (fdiv.jl:138) — the last row's span, 64 lanes, inside the caller's
 * own region. `const`, for cq_mul_product's reason: inside one compute half it
 * is a CONTROL for whatever comes next, and a consumer that WROTE into it
 * would make the reverse half non-cancelling. */
const cq_bit *cq_fdiv_result(const cq_fdiv_block *k);

/* Risk R9's classical row: the SAME Julia body evaluated in C over `uint64_t`
 * (PRD-v2 §7.4), composing M31's and M32's `*_eval` bodies, NEVER the host
 * `double` `/`. Four of §7.4's five IEEE-unspecified cells are reachable from
 * `fdiv` — `0/0` and `Inf/Inf` both give x86's INDEF, and the three NaN
 * payload cells go through `_sf_propagate_nan2` — and every one of them is
 * x86's choice; this way the classical and quantum modes agree bit-for-bit on
 * every host. It is NOT an L1 oracle — that is the host operator with those
 * cells pinned by table (tests/support/fphost.h). */
uint64_t cq_fdiv_eval(uint64_t a, uint64_t b);

/* --- The Rule 7 kernel. --------------------------------------------------- */

/* `dst ^= soft_fdiv(a, b)`, with `a` and `b` 64 bits and unchanged and every
 * internal ancilla back at |0>. `W` must be 64. There is no `_unc` entry point
 * (uncompute is the same call) and no `_controlled` variant (the axis is an
 * emitter mode). Rule 7's canonical shape, unchanged, so it is storable in a
 * `cq_kernel_fn` and the shared Phase-B driver drives it with no adapter. */
void cq_kernel_fdiv(cq_ctx *ctx, cq_bit *dst,
                    const cq_bit *a, const cq_bit *b, int W);

#endif /* CQOPS_KERNELS_FDIV_H */
