#!/bin/sh
# check_loc.sh — the 300-line guard (CLAUDE.md Rule 12, IMPLEMENTATION_PLAN §2.3).
#
# Fails if any hand-written .c / .h / .py under src/ include/ tests/ shim/
# tools/ exceeds the limit in non-blank, non-comment lines.
#
# THE ROOT SET IS THE `for d in ...` LOOP BELOW AND NOTHING ELSE — no test and
# no CMake file pins it, which is how three documents drifted from it
# unnoticed (a line number here would rot the same way). Corrected
# 2026-09-10 (bd dtb): this header, CLAUDE.md Rule 12 and plan §2.3 all named
# FOUR roots, omitting tools/, while the loop has named five since Step 1. That
# was reasonable while tools/ held only this script, which is a .sh and so is
# never matched by the find below; the Step 24 L6 harness put the first .py
# under it, and measured today tools/ holds 16 countable files whose largest,
# tools/l6/l6_run.py, is within twenty lines of the limit. The code is
# authoritative; the comment was stale, not the loop.
#
# One live consequence of that fifth root, measured 2026-09-10: this script
# walks the FILESYSTEM, not the git index, and tools/qtg/ is gitignored — so
# 9 of those 16 files exist only on a box that has them. The file COUNT this
# script prints is therefore not reproducible across checkouts (203 here, 194
# tracked). The limit it enforces is per-file and is unaffected.
#
# Exempt:
#   *.gen.c        generated by shim/gen_shim.py (M28)
#   third_party/   not ours; also outside the scanned roots
#   *.inc          Rule 12 counts .c/.h/.py only, which is what makes "move
#                  the big static table into an .inc" a real escape hatch
#                  rather than a rename that dodges the guard
#
# Hitting the limit is a scheduled split, not a surprise refactor: every module
# over ~200 lines already names its split seam in plan §3.
#
# Comment stripping is deliberately conservative. A line is dropped only when
# its FIRST non-space characters open a comment (// or # or /*); a trailing
# comment leaves its line counted, which is correct, since the line has code on
# it. The rule therefore never has to decide whether a // or /* sits inside a
# string literal. Python docstrings are counted as code — over-counting is the
# safe direction for a guard.

set -eu

limit="${CQOPS_LOC_LIMIT:-300}"
root="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$root"

count_lines() {
    # $1 = path, $2 = lang ("c" or "py")
    awk -v lang="$2" '
        BEGIN { in_block = 0; n = 0 }
        {
            line = $0
            sub(/^[ \t]+/, "", line)

            if (in_block) {
                if (line ~ /\*\//) {
                    sub(/^.*\*\//, "", line)
                    in_block = 0
                    sub(/^[ \t]+/, "", line)
                } else {
                    next
                }
            }

            if (line == "") next

            if (lang == "py") {
                if (line ~ /^#/) next
            } else {
                if (line ~ /^\/\//) next
                if (line ~ /^\/\*/) {
                    if (line ~ /\*\//) {
                        sub(/^\/\*.*\*\//, "", line)
                        sub(/^[ \t]+/, "", line)
                        if (line == "") next
                    } else {
                        in_block = 1
                        next
                    }
                }
            }

            n++
        }
        END { print n }
    ' "$1"
}

roots=''
for d in src include tests shim tools; do
    [ -d "$d" ] && roots="$roots $d"
done

if [ -z "$roots" ]; then
    echo "check_loc: no source roots yet — nothing to check"
    exit 0
fi

# shellcheck disable=SC2086
files=$(find $roots -type f \( -name '*.c' -o -name '*.h' -o -name '*.py' \) \
        | grep -v '\.gen\.c$' \
        | sort)

status=0
checked=0
max=0
max_file='(none)'

for f in $files; do
    case "$f" in
        *.py) lang=py ;;
        *)    lang=c  ;;
    esac

    n=$(count_lines "$f" "$lang")
    checked=$((checked + 1))

    if [ "$n" -gt "$max" ]; then
        max=$n
        max_file=$f
    fi

    if [ "$n" -gt "$limit" ]; then
        echo "check_loc: FAIL $f — $n lines (limit $limit)"
        echo "           split it along the seam named in IMPLEMENTATION_PLAN §3;"
        echo "           a large static test table belongs in an .inc file."
        status=1
    fi
done

if [ "$checked" -eq 0 ]; then
    echo "check_loc: no hand-written .c/.h/.py found under$roots"
    exit 0
fi

if [ "$status" -eq 0 ]; then
    echo "check_loc: OK — $checked file(s), limit $limit, largest $max ($max_file)"
fi

exit "$status"
